#!/usr/bin/env node
var debug = require('debug')('imit-new');
var app = require('../app');
var settings = require('./settings');

app.set('port', process.env.PORT || settings.APP_PORT);

var server = app.listen(app.get('port'), function() {
  debug('Express server listening on port ' + server.address().port);
});
